#!/usr/bin/env python3
import sys

# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N, Q = [int(x) for x in sys.stdin.readline().split()]
    nums = []
    for i in range(N):
        nums.append([int(x) for x in sys.stdin.readline().split()])
    for i in range(Q):
        s, t = [int(x) for x in sys.stdin.readline().split()]
        print(nums[s-1][t])


if __name__ == '__main__':
    main()
