#!/usr/bin/env python3
import sys


def solve(X: int):
    hist = []
    order = 1
    buf = []
    buf.append(0)
    while X != 0:
        if X & 1:
            for h in list(hist):
                new_h = order | h
                buf.append(new_h)
                hist.append(new_h)
            hist.append(order)
            buf.append(order)
        order <<= 1
        X >>= 1
    buf.sort()
    for i in buf:
        print(i)

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    solve(X)

if __name__ == '__main__':
    main()
