#!/usr/bin/env python3
import sys


def solve(N: int):
    exp = 0.0
    for i in range(N, 0, -1):
        cnt = 0
        sum = 0.0
        for j in range(1, 7):
            if j > exp:
                cnt += 1
                sum += j
        if cnt == 6:
            exp = sum / cnt
        else:
            rate = (6 - cnt) / 6.0
            exp = exp * rate + (1-rate) * sum / cnt
    print(exp)

    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
