#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;



// Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    // Failed to predict input format
    long long N;
    std::scanf("%lld", &N);
    deque<pair<long long, long long> > v;
    for(long long i = 0; i < N; i++){
        long long t, x, c;
        cin >> t;
        if (t == 1) {
            cin >> x;
            cin >> c;
            v.push_back(make_pair(x, c));
        } else {
            cin >> c;
            long long val = 0;
            while(!v.empty() && c > 0) {
                auto p = v.front();
                if (p.second > c) {
                    v.pop_front();
                    v.push_front(make_pair(p.first, p.second - c));
                    val += c * p.first;
                    c = 0;
                } else {
                    val += p.second * p.first;
                    c -= p.second;
                    v.pop_front();
                }
            }
            cout << val << endl;
        }
    }
    return 0;
}
